### PR TITLE
Add plugin cerebrp-nzh

### PR DESCRIPTION
**Pull request by carlos-wong**

### CODE REVIEW

**Comment by lubien** [comment]
For the sake of consistency would you mind adding a "." at the end of your sentence. I'd also ask you to make just one commit for this PR.

Thanks for contributing!

**Comment by lubien** [comment]
Just realized there's a typo in your commit title, mind fixing that too?

**Comment by carlos-wong** [comment]
@lubien Hi, commit log fixed

**Comment by lubien** [comment]
Mind making it a single commit?

**Comment by lubien** [comment]
Thanks for your contribution!

**Pull request merged**
