### PR TITLE
Add Cerebro-base64 Plugin

### PR DESCRIPTION
**Pull request by Krbz**
Add Cerebro-base64 Plugin

### CODE REVIEW

**Comment by lubien** [comment]
Hi there.

Your commit is missing a full stop. Can you edit it? (One commit/PR is best).

**Comment by lubien** [comment]
Hi there. Any updates on this?

**Comment by Krbz** [comment]
Hi, I will close PR. After that I will open a new one with full stop, thanks!

**Comment by lubien** [comment]
Don't problem. But you could have force pushed a new commit overwritting these one

**Pull request closed without merging**
