### PR TITLE
Add cerebro article

### LINKED ISSUE #10: Cerebro article
I wrote an [article](https://github.com/BrainMaestro/primer/blob/master/react/building-small-apps-with-react-cerebro.md) that walks users through creating a simple cerebro plugin. Might be useful for new developers. Is that something that could be in this repository? Or is it solely for plugins?

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #10

### CODE REVIEW

**Comment by lubien** [comment]
Hi there. A couple issues:

1. As said in #10 "You should make a category [...] named Articles **after the others**".
2. As of [Contribution Guidelines](CONTRIBUTING.md) "Make an **individual pull request** for each suggestion", so your plugin and article should come in separate PRs :D

Just be sure to make one commit/PR so you can overwrite this one.

**Comment by lubien** [comment]
Jut one more issue: you forgot a full stop at the end of the article link.

**Comment by BrainMaestro** [comment]
Done

**Comment by lubien** [comment]
Great

**Pull request merged**
