### PR TITLE
packagist plugin included on main list

### PR DESCRIPTION
**Pull request by rafa-acioly**

### CODE REVIEW

**Comment by lubien** [comment]
Thanks for erasing the trailing space I didn't see, I appreciate that.

Can you make these into two commits so the Git tree is more concise?

**Comment by rafa-acioly** [comment]
I think that i've done it now. please reject the unnecessary commits

**Comment by lubien** [comment]
I think it's best for you to overwritte all these commits with the two proper ones.

Also, commit names as "part 1" and "part 2" will be confusing on the Git tree, I need you to properly name them.

**Comment by rafa-acioly** [comment]
please, reject this pull request, i'll start over.

**Comment by lubien** [comment]
You don't need to make another PR, just force push the fix here overwriting the unwanted commits :)

**Comment by lubien** [comment]
Perfect!

**Pull request merged**
